// <auto-generated />
using System;
using ClimateControlSystem.Server.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClimateControlSystem.Server.Migrations
{
    [DbContext(typeof(PredictionsDbContext))]
    [Migration("20221115045314_InitialiseDb")]
    partial class InitialiseDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClimateControlSystem.Server.Resources.RepositoryResources.MonitoringDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("AirDryTemperatureOutside")
                        .HasColumnType("real");

                    b.Property<float>("AirHumidityOutside")
                        .HasColumnType("real");

                    b.Property<float>("AirWetTemperatureOutside")
                        .HasColumnType("real");

                    b.Property<float>("ClusterLoad")
                        .HasColumnType("real");

                    b.Property<float>("ClusterTemperature")
                        .HasColumnType("real");

                    b.Property<float>("CpuUsage")
                        .HasColumnType("real");

                    b.Property<float>("MeanCoolingValue")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("MeasurementTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<float>("PredictedHumidity")
                        .HasColumnType("real");

                    b.Property<float?>("PredictedHumidityAccuracy")
                        .HasColumnType("real");

                    b.Property<float>("PredictedTemperature")
                        .HasColumnType("real");

                    b.Property<float?>("PredictedTemperatureAccuracy")
                        .HasColumnType("real");

                    b.Property<float>("PreviousHumidity")
                        .HasColumnType("real");

                    b.Property<float>("PreviousTemperature")
                        .HasColumnType("real");

                    b.Property<float>("WindDirection")
                        .HasColumnType("real");

                    b.Property<float>("WindEnthalpy")
                        .HasColumnType("real");

                    b.Property<float>("WindSpeed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("MonitoringData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirDryTemperatureOutside = -3f,
                            AirHumidityOutside = 91f,
                            AirWetTemperatureOutside = -3.91f,
                            ClusterLoad = 50.8f,
                            ClusterTemperature = 56f,
                            CpuUsage = 5945.632f,
                            MeanCoolingValue = 17.7f,
                            MeasurementTime = new DateTimeOffset(new DateTime(2022, 11, 15, 9, 53, 14, 549, DateTimeKind.Unspecified).AddTicks(7676), new TimeSpan(0, 5, 0, 0, 0)),
                            PredictedHumidity = 18.77f,
                            PredictedTemperature = 23.32f,
                            PreviousHumidity = 19.71f,
                            PreviousTemperature = 23.48f,
                            WindDirection = 225f,
                            WindEnthalpy = -4.06f,
                            WindSpeed = 3f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
